name: Validate Detection Rules (PR Only)

on:
  pull_request:
    paths:
      - 'detections/rules/**/*.yaml'

jobs:
  validate:
    name: Run detections/tests/validation_script_main.py
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use system Python
      run: |
        python --version
        python detections/tests/validation_script_main.py

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install cerberus croniter pyyaml requests matplotlib splunklib matplotlib urllib3

    - name: Inject config.json for Splunk Access
      run: |
        echo "Creating config.json from secrets..."
        cat <<EOF > config.json
        {
          "host": "https://splunk-host:8089",
          "username": "${{ secrets.SPLUNK_USERNAME }}",
          "password": "${{ secrets.SPLUNK_PASSWORD }}",
          "app": "search"
        }
        EOF
        echo "✅ config.json created"

    - name: Run Detection Rule Validation
      run: |
        source venv/bin/activate
        echo "🚦 Starting validation..."
        python detections/tests/validation_script_main.py
